repos:
-   repo: https://github.com/python/black
    rev: 21.7b0
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        language: python_venv
        additional_dependencies: [flake8-comprehensions>=3.1.0]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
        language: python_venv
