version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dm3k_api
    restart: always
    volumes:
      - ./api/:/app/api
      - ./optimizer/:/app/optimizer
      - ./tests/:/app/tests
      - ./examples/:/app/examples
    expose:
      - 9000
    
  ui:
    build: ./ui
    container_name: dm3k_ui
    restart: always
    expose:
      - 80

  nginx:
    build: ./nginx
    container_name: dm3k_nginx
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail -s http://localhost/api/version || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3


