version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    container_name: dm3k_open_api
    restart: always
    volumes:
      - ./api/:/app/api
      - ./optimizer/:/app/optimizer
      - ./tests/:/app/tests
      - ./examples/:/app/examples
    expose:
      - 5000
    
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: dm3k_open_nginx
    restart: always
    ports:
      - "80:80"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: dm3k_open_ui
    restart: always
    volumes:
      - ./ui/:/app
    expose:
      - 8080
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true