version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dm3k_open_api
    restart: always
    volumes:
      - ./api/:/app/api
      - ./optimizer/:/app/optimizer
      - ./tests/:/app/tests
      - ./examples/:/app/examples
    expose:
      - 9000
    
  ui:
    build: ./ui
    container_name: dm3k_open_ui
    restart: always
    expose:
      - 80

  nginx:
    build: ./nginx
    container_name: dm3k_open_nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:80"

