version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    container_name: dm3k_open_api
    restart: always
    volumes:
      - ./api/:/app/api
      - ./optimizer/:/app/optimizer
      - ./tests/:/app/tests
      - ./examples/:/app/examples
    expose:
      - 5000
    
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: dm3k_open_nginx
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail -s http://localhost/api/version || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: dm3k_open_ui
    restart: always
    volumes:
    # trying to avoid copying out node_modules into local system (this causes errors if local node-modules becomes out of date with build node_modules) 
    # but still getting hot reloads
      - ./ui/public:/app/public
      - ./ui/src:/app/src
    expose:
      - 8080
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    