# build stage
FROM node:12.14.0-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN yarn config set strict-ssl false 
RUN yarn

# didnt 'COPY . .' # danger this copies over node_modules or yarn.lock if this folder is local
COPY ./public ./public
COPY ./src ./src

# copy over vue and babel configs
COPY *config.js ./   

EXPOSE 8080

CMD ["yarn", "serve"]