FROM python:3.7.2
WORKDIR /app
RUN mkdir api
ADD . /app/api

RUN mkdir examples
ADD ../examples /app/examples
RUN mkdir optimzer
ADD ../optimizer /app/optimizer
RUN mkdir tests
ADD ../tests /app/tests

# RUN pip install -r requirements.txt
# CMD ["python", "run.py", "--debug"]
